services:
  chatapplication.webapi:
    image: ${DOCKER_REGISTRY-}chatapplicationwebapi
    build:
      context: .
      dockerfile: ChatApplication/Dockerfile
    depends_on:
      - postgres-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=chatdb;Username=chatuser;Password=Teste123
    ports:
      - "8081:8081"
    tty: true

  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: Teste123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
