services:
  chatapplication.webapi:
    image: chatapplicationwebapi:dev
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ChatApplication.webApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_chatapplication.webapi$
    volumes:
      - C:\Users\alves\Downloads\ProjetoDeExtensaoEmProgramacao\ChatApplication:/app:rw
      - C:\Users\alves\Downloads\ProjetoDeExtensaoEmProgramacao:/src:rw
      - C:\Users\alves\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_chatapplication.webapi$
      - C:\Users\alves\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\alves\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\alves\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\alves\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\18\Insiders\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\18\Insiders\Common7\IDE\extensions\Microsoft\managedprojectsystem\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_chatapplication.webapi$ \"/app/bin/Debug/net8.0/ChatApplication.webApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true